name: Testes Mobile com Robot Framework

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Instalar o Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Instalar Docker Compose
        run: |
          sudo apt install -y docker-compose

      - name: Subir ambiente com Docker Compose
        run: |
          docker compose up -d

      - name: Aguardar container iniciar
        run: sleep 40

      - name: Executar os testes
        run: |
          source venv/bin/activate
          robot --outputdir results/ .

      - name: Salvar artefatos (relatórios)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorios-de-teste
          path: results/

  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-24.04
    if: always()
    needs:
      - run-tests

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://andre-min.github.io/testing-mobile/report.html
      
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: relatorios-de-teste
          path: results/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: results/

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4


    