name: Testes Mobile com Robot Framework

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências e criar ambiente virtual
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar Docker no ambiente
        uses: docker/setup-buildx-action@v3

      - name: Subir ambiente com Docker Compose
        run: docker compose up -d

      - name: Aguardar containers inicializarem
        run: sleep 40

      - name: Executar testes Robot Framework
        run: |
          . venv/bin/activate
          robot --outputdir results/ .

      - name: Salvar artefatos (relatórios)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorios-de-teste
          path: results/

  deploy:
    name: Deploy no GitHub Pages
    runs-on: ubuntu-24.04
    if: always()
    needs:
      - run-tests

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://andre-min.github.io/testing-mobile/report.html

    steps:
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Baixar artefatos (relatórios)
        uses: actions/download-artifact@v4
        with:
          name: relatorios-de-teste
          path: results/

      - name: Fazer upload dos relatórios para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: results/

      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
